all: lab2.c lista.c stack.c
	gcc -Wall lab2.c lista.c stack.c -lm -o lab2

a: lab2.c lista.c stack.c
	gcc -Wall lab2.c lista.c stack.c -lm -o lab2
	./lab2 a

b: lab2.c lista.c stack.c
	gcc -Wall lab2.c lista.c stack.c -lm -o lab2
	./lab2 b
